### ISSUE TITLE
Can't get Groups to work

### ISSUE THREAD

**Issue by robertsimmons** [Hyperioxes/HyperTools#1]
Hi! I've used WeakAuras a bunch, so I was excited to see this add-on available.

However, I can't seem to get groups to work (not the group member thing, just a group of auras together). I click "Create New", pick "Group". My new one shows up in the list. I click the "down" arrow thing to go "inside" it. Now the left says "create new" and "return".

I hit "create new", pick any of those options, Add a name, add a spell id, hit "create". Nothing shows up on the left. I hit "return" to go back to main list, and it has made it, just not inside my group.

I've tried making sure I've selected the group before clicking the down arrow to go inside it, and that didn't help. I tried deleting the saved variables and reinstalling it (via Minion), and that didn't fix anything - which didn't surprise me, as I had just freshly installed it anyways.

The current version bugged, or am I missing something here?

**Comment by robertsimmons** [comment]
As an update - tried installing 0.11, same issue.

**Comment by Hyperioxes** [comment]
Hi, there's no way to create a tracker inside a group, you have to create it outside and then put it inside of a group by selecting the tracker and then Ctrl+clicking the group (I'm not sure if I put that information anywhere, if not I'll make sure to add a tooltip about it in next patch). I'll add the option to create trackers inside of a group to my todo list but at the moment I'm busy making a website for tracker sharing

**Comment by robertsimmons** [comment]
Ah, sorry! I missed that in the wiki. I see it now.

I'm having trouble getting the "In Combat" detection to work properly, but other than that, I think I'm making progress now. Thanks again for the hard work!
